select = [
  "A",
  "ANN",
  "ARG",
  "B",
  "C4",
  "COM",
  "E",
  "F",
  "FA",
  "FLY",
  "FURB",
  "I",
  "ISC",
  "N",
  "PERF",
  "PIE",
  "PL",
  "Q",
  "RET",
  "RSE",
  "RUF",
  "S",
  "SIM",
  "TCH",
  "TRY",
  "UP",
  "W",
]
ignore = ["ANN101", "ANN102", "ANN401", "S101", "PLR0913", "PLR2004"]
exclude = ["base.py"]
